version: '3'
services:
  pyapp:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/code/static
      - ./.env:/code/.env
    ports:
      - "5500:80"
    healthcheck:
      test: ["CMD", "curl -f", "http://localhost/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s